name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure kubeconfig
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

      - name: Rollout Restart Frontend
        run: |
          kubectl rollout restart deployment/frontend -n jamal
          kubectl rollout status deployment/frontend -n jamal
